//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjTecso.ej3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Curso()
        {
            this.Inscripcion = new HashSet<Inscripcion>();
        }
    
        public int IDCurso { get; set; }
        public int IDMateria { get; set; }
        public int CupoMaximo { get; set; }
        public int IDDocente { get; set; }
        public System.DateTime FechaInscripcionInicio { get; set; }
        public System.DateTime FechaInscripcionFin { get; set; }
        public System.DateTime FechaInicioCursada { get; set; }
        public System.DateTime FechaFinCursada { get; set; }
    
        public virtual Docente Docente { get; set; }
        public virtual Materia Materia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inscripcion> Inscripcion { get; set; }
    }
}
