//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjTecso.ej3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inscripcion
    {
        public int IDAlumno { get; set; }
        public int IDCurso { get; set; }
        public System.DateTime FechaInscripcion { get; set; }
        public int IDEstado { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Curso Curso { get; set; }
        public virtual Inscripcion_Estado Inscripcion_Estado { get; set; }
    }
}
